export const styles = {
  container: "min-h-screen bg-white",
  hero: {
    section: "relative isolate overflow-hidden bg-gray-900 py-24 sm:py-32",
    image: "absolute inset-0 -z-10 h-full w-full object-cover opacity-20",
    gradient: "absolute inset-0 -z-10 bg-gradient-to-t from-gray-900 via-gray-900/40",
    contentWrapper: "mx-auto max-w-7xl px-6 lg:px-8",
    content: "mx-auto max-w-2xl lg:mx-0",
    title: "text-4xl font-bold tracking-tight text-white sm:text-6xl",
    subtitle: "mt-6 text-lg leading-8 text-gray-300",
  },
  mission: {
    section: "mx-auto max-w-7xl px-6 lg:px-8 py-24 sm:py-32",
    grid: "mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3",
    title: "text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl",
    description: "mt-6 text-lg leading-8 text-gray-600",
    statsGrid: "grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-1",
    statCard: "flex flex-col gap-y-3 border-l border-indigo-600 pl-6",
    statValue: "text-3xl font-bold tracking-tight text-gray-900",
    statLabel: "text-sm leading-6 text-gray-600",
  },
  values: {
    section: "bg-gray-50 py-24 sm:py-32",
    container: "mx-auto max-w-7xl px-6 lg:px-8",
    header: "mx-auto max-w-2xl lg:mx-0",
    title: "text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl",
    subtitle: "mt-6 text-lg leading-8 text-gray-600",
    grid: "mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 text-base leading-7 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3",
    card: "relative pl-9",
    icon: "absolute left-0 top-1 h-5 w-5 text-indigo-600",
    cardTitle: "font-semibold text-gray-900 inline",
    cardDesc: "inline",
  },
  team: {
    section: "py-24 sm:py-32",
    container: "mx-auto max-w-7xl px-6 lg:px-8",
    header: "mx-auto max-w-2xl lg:mx-0",
    title: "text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl",
    subtitle: "mt-6 text-lg leading-8 text-gray-600",
    grid: "mx-auto mt-20 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3",
    card: "text-center",
    image: "mx-auto h-24 w-24 rounded-full object-cover",
    name: "mt-6 text-base font-semibold leading-7 tracking-tight text-gray-900",
    role: "text-sm leading-6 text-gray-600",
  }
};
