export const styles = {
  overlay: "fixed inset-0 z-50 bg-black/50 backdrop-blur-sm",
  drawer: "fixed top-0 right-0 z-50 h-full w-full max-w-md bg-white shadow-xl transition-transform duration-300 ease-in-out",
  drawerOpen: "translate-x-0",
  drawerClosed: "translate-x-full",
  container: "flex h-full flex-col",
  header: "flex items-center justify-between border-b border-gray-200 px-6 py-4",
  title: "text-lg font-semibold text-gray-900",
  closeButton: "rounded-full p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500",
  body: "flex-1 overflow-y-auto px-6 py-4",
  emptyState: "flex h-full flex-col items-center justify-center text-center",
  emptyIcon: "mb-4 text-gray-300",
  emptyText: "text-gray-500",
  footer: "border-t border-gray-200 bg-gray-50 px-6 py-6",
  totalRow: "flex items-center justify-between mb-4",
  totalLabel: "text-base font-medium text-gray-900",
  totalValue: "text-lg font-bold text-gray-900",
  checkoutButton: "w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-50 disabled:cursor-not-allowed",
};
